### ISSUE TITLE
Create Location Pages

### ISSUE THREAD

**Issue by 20annageorge** [oliverj96/katy_trail_app#11]
Create location pages (for now, create a location page template since we don't have data yet). Will include pictures, text, and audio.

**Comment by oliverj96** [comment]
- Dynamically add description and images as needed
- Changes sample data content to contain a list of images
- Change sample data content to contain a list of description
- Pass all data from explore card to explore page
- Pass the specific location details form explore list to explore card
- Create location page, explore card template, and list container.
