### ISSUE TITLE
Import Firebase API and create Firebase Project

### ISSUE THREAD

**Issue by oliverj96** [oliverj96/katy_trail_app#8]
In the main page, try importing firebase API and creating a project. Test bringing in data (database does not have to be well constructed yet, just try getting any proof of connectivity to work). 

Please fork for testing. Once you finish testing, then create a new branch from this repo and just add the necessary imports.

**Comment by Niralipatel1710** [comment]
https://console.firebase.google.com/u/0/project/katy-trail/database/firestore/data~2F 

Here is database project on firebase.
